name: Tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  unit-tests:
    runs-on: macos-11
    name: Runs unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select xcode
        run: sudo xcode-select -s "/Applications/Xcode_13.0.app"
      - name: Install xcodegen
        run: |
          brew install xcodegen
      - name: Print swiftlint & xcodegen versions
        run: |
          swiftlint version
          xcodegen version
      - name: Generate .xcodeproj file
        run: ./Scripts/Generate.sh
      - name: Run unit tests
        run: ./Scripts/RunUnitTests.sh
      - name: Gather code coverage
        run: ./Scripts/RunCodecov.sh
  ui-tests:
    runs-on: macos-11
    name: Runs UI tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select xcode
        run: sudo xcode-select -s "/Applications/Xcode_13.0.app"
      - name: Install xcodegen
        run: |
          brew install xcodegen
      - name: Print swiftlint & xcodegen versions
        run: |
          swiftlint version
          xcodegen version
      - name: Generate .xcodeproj file
        run: ./Scripts/Generate.sh
      - name: Run UI tests
        run: ./Scripts/RunUiTests.sh
