name: Tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  unit-tests:
    runs-on: macos-12
    name: Runs iOS unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select xcode
        run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
      - name: Install xcodegen
        run: |
          brew install xcodegen
      - name: Print swiftlint & xcodegen versions
        run: |
          swiftlint version
          xcodegen version
      - name: Generate .xcodeproj file
        run: rake project:generate
      - name: Run iOS unit tests
        run: ./Scripts/RuniOSUnitTests.sh
  ui-tests:
    runs-on: macos-12
    name: Runs iOS UI tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select xcode
        run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
      - name: Install xcodegen
        run: |
          brew install xcodegen
      - name: Print swiftlint & xcodegen versions
        run: |
          swiftlint version
          xcodegen version
      - name: Generate .xcodeproj file
        run: rake project:generate
      - name: Run iOS UI tests
        run: ./Scripts/RuniOSUiTests.sh
